// Code generated by protoc-gen-zig
///! package api.command
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const Command = struct {
    path: ManagedString = .Empty,
    args: ArrayList(ManagedString),
    cwd: ?ManagedString = null,

    pub const _desc_table = .{
        .path = fd(1, .String),
        .args = fd(2, .{ .List = .String }),
        .cwd = fd(3, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
