// Code generated by protoc-gen-zig
///! package api.file
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const File = struct {
    path: ManagedString = .Empty,
    line_number: ?i32 = null,
    cwd: ?ManagedString = null,

    pub const _desc_table = .{
        .path = fd(1, .String),
        .line_number = fd(2, .{ .Varint = .Simple }),
        .cwd = fd(3, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
