// Code generated by protoc-gen-zig
///! package api.input_mode
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const InputMode = enum(i32) {
    Normal = 0,
    Locked = 1,
    Resize = 2,
    Pane = 3,
    Tab = 4,
    Scroll = 5,
    EnterSearch = 6,
    Search = 7,
    RenameTab = 8,
    RenamePane = 9,
    Session = 10,
    Move = 11,
    Prompt = 12,
    Tmux = 13,
    _,
};

pub const InputModeMessage = struct {
    input_mode: InputMode = @enumFromInt(0),

    pub const _desc_table = .{
        .input_mode = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
