// Code generated by protoc-gen-zig
///! package api.key
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const Key = struct {
    modifier: ?KeyModifier = null,
    main_key: ?main_key_union,

    pub const _main_key_case = enum {
        key,
        char,
    };
    pub const main_key_union = union(_main_key_case) {
        key: NamedKey,
        char: Char,
        pub const _union_desc = .{
            .key = fd(2, .{ .Varint = .Simple }),
            .char = fd(3, .{ .Varint = .Simple }),
        };
    };

    pub const _desc_table = .{
        .modifier = fd(1, .{ .Varint = .Simple }),
        .main_key = fd(null, .{ .OneOf = main_key_union }),
    };

    pub const KeyModifier = enum(i32) {
        CTRL = 0,
        ALT = 1,
        _,
    };

    pub const NamedKey = enum(i32) {
        PageDown = 0,
        PageUp = 1,
        LeftArrow = 2,
        DownArrow = 3,
        UpArrow = 4,
        RightArrow = 5,
        Home = 6,
        End = 7,
        Backspace = 8,
        Delete = 9,
        Insert = 10,
        F1 = 11,
        F2 = 12,
        F3 = 13,
        F4 = 14,
        F5 = 15,
        F6 = 16,
        F7 = 17,
        F8 = 18,
        F9 = 19,
        F10 = 20,
        F11 = 21,
        F12 = 22,
        Tab = 23,
        Esc = 24,
        _,
    };

    pub const Char = enum(i32) {
        a = 0,
        b = 1,
        c = 2,
        d = 3,
        e = 4,
        f = 5,
        g = 6,
        h = 7,
        i = 8,
        j = 9,
        k = 10,
        l = 11,
        m = 12,
        n = 13,
        o = 14,
        p = 15,
        q = 16,
        r = 17,
        s = 18,
        t = 19,
        u = 20,
        v = 21,
        w = 22,
        x = 23,
        y = 24,
        z = 25,
        zero = 26,
        one = 27,
        two = 28,
        three = 29,
        four = 30,
        five = 31,
        six = 32,
        seven = 33,
        eight = 34,
        nine = 35,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
