// Code generated by protoc-gen-zig
///! package api.message
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const Message = struct {
    name: ManagedString = .Empty,
    payload: ManagedString = .Empty,
    worker_name: ?ManagedString = null,

    pub const _desc_table = .{
        .name = fd(1, .String),
        .payload = fd(2, .String),
        .worker_name = fd(3, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
